### Numpy: Package for Multidimensional array

In [4]:
import numpy as np

In [5]:
simple_list=[6,7,8]
np.array(simple_list)

array([6, 7, 8])

In [6]:
list_of_lists=[[3,4,5],[2,6,7],[1,8,9]]
np.array(list_of_lists)

array([[3, 4, 5],
       [2, 6, 7],
       [1, 8, 9]])

In [7]:
np.arange (5,20)








array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
np.arange(1,36,5)

array([ 1,  6, 11, 16, 21, 26, 31])

In [10]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros(30,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones(20,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.linspace(0,2,4)

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [16]:
np.linspace(0,50,8)

array([ 0.        ,  7.14285714, 14.28571429, 21.42857143, 28.57142857,
       35.71428571, 42.85714286, 50.        ])

In [17]:
np.eye(15,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [18]:
np.random.rand(6,5)

array([[0.68506303, 0.40742521, 0.58474447, 0.70775594, 0.16472235],
       [0.71452035, 0.34220638, 0.59473146, 0.8016018 , 0.41124377],
       [0.12918677, 0.31997807, 0.04811567, 0.27231949, 0.2469212 ],
       [0.28101237, 0.86068132, 0.55351836, 0.56263199, 0.17334734],
       [0.15820185, 0.55023627, 0.997227  , 0.52424533, 0.99581641],
       [0.92196891, 0.02462593, 0.69284224, 0.28355803, 0.68873829]])

In [19]:
arr=np.random.randn(2,4)
arr

array([[-0.93895792, -1.37515024,  0.25780265,  0.7590627 ],
       [ 1.79211427,  0.03562464,  1.33773345, -1.74064187]])

In [20]:
np.random.randint(6,100)

90

In [21]:
np.random.randint(20,56,100)

array([23, 34, 45, 35, 21, 38, 25, 36, 32, 25, 24, 43, 28, 50, 39, 23, 33,
       38, 49, 42, 54, 30, 46, 51, 55, 55, 21, 20, 34, 26, 43, 26, 55, 43,
       32, 55, 36, 23, 29, 48, 23, 43, 20, 35, 32, 32, 38, 21, 32, 42, 49,
       50, 43, 42, 35, 26, 35, 25, 55, 54, 20, 51, 41, 43, 48, 40, 25, 35,
       34, 25, 35, 45, 40, 35, 40, 54, 52, 28, 21, 36, 37, 21, 48, 35, 50,
       29, 26, 50, 40, 54, 34, 39, 46, 46, 25, 46, 22, 54, 51, 54])

In [22]:
sample_array=np.arange(35)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [23]:
rand_array=np.random.randint(0,10,50)
rand_array

array([9, 5, 1, 6, 3, 7, 1, 2, 1, 1, 2, 8, 7, 8, 7, 4, 1, 3, 0, 7, 0, 1,
       0, 9, 2, 9, 4, 6, 1, 6, 3, 8, 4, 6, 8, 4, 0, 8, 5, 2, 2, 3, 5, 0,
       3, 8, 0, 6, 6, 3])

In [24]:
sample_array.reshape(5,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [25]:
rand_array.max()

9

In [26]:
rand_array.argmax()

0

In [27]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
a=np.random.rand(2,3)
a

array([[0.18796398, 0.96861226, 0.78752849],
       [0.92713203, 0.10981434, 0.92919525]])

In [30]:
a.T

array([[0.18796398, 0.92713203],
       [0.96861226, 0.10981434],
       [0.78752849, 0.92919525]])

In [31]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [32]:
sample_array[10]

20

In [33]:
sample_array[2:5]

array([12, 13, 14])

In [34]:
sample_array[1:5]=100
sample_array

array([ 10, 100, 100, 100, 100,  15,  16,  17,  18,  19,  20])

In [35]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
sample_array[0:5]

array([10, 11, 12, 13, 14])

In [37]:
subset_sample_array= sample_array[0:4]
subset_sample_array

array([10, 11, 12, 13])

In [38]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001])

### Two-Dimensional array

In [39]:
import numpy as np

In [40]:
sample_matrix=np.array([[50,3,2,],[6,8,9],[23,67,89]])
sample_matrix

array([[50,  3,  2],
       [ 6,  8,  9],
       [23, 67, 89]])

In [41]:
sample_matrix[2,1]

67

In [42]:
sample_matrix[2,:]

array([23, 67, 89])

In [43]:
sample_matrix[1]

array([6, 8, 9])

In [44]:
sample_matrix[:,(0,1)]

array([[50,  3],
       [ 6,  8],
       [23, 67]])

### selection techniques

In [45]:
sample_array=np.arange(1,30)

In [46]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [47]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [48]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12])

In [49]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481])

In [50]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583])

In [51]:
np.max(sample_array)

29

In [52]:
np.min(sample_array)

1

In [53]:
np.argmax(sample_array)

28

In [54]:
np.argmin(sample_array)

0

In [55]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841])

In [56]:
np.std(sample_array)

8.366600265340756

In [57]:
np.var(sample_array)

70.0

In [58]:
np.mean(sample_array)

15.0

In [ ]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

In [ ]:
### pandas


In [3]:
import numpy as np
import pandas as pd

### Pandas dataframes and indexing

In [5]:
sports1=pd.Series([2,4,5,6],index=['cricket','football','basketball','golf'])
sports1

cricket       2
football      4
basketball    5
golf          6
dtype: int64

In [7]:
sports1['football']

4

In [8]:
sports2=pd.Series([8,9,7,4],index=['cricket','baseball','basketball','golf'])
sports2

cricket       8
baseball      9
basketball    7
golf          4
dtype: int64

In [9]:
sports1+sports2

baseball       NaN
basketball    12.0
cricket       10.0
football       NaN
golf          10.0
dtype: float64

In [11]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.244003  0.261064  0.484532  0.439343  0.440695
B  0.924249  0.350629  0.451532  0.920795  0.501744
C  0.033633  0.303336  0.295935  0.778055  0.478633
D  0.493485  0.134175  0.533664  0.849704  0.948651
E  0.558038  0.527210  0.705029  0.135567  0.916620
F  0.366130  0.239166  0.099890  0.332609  0.456562
G  0.461912  0.181772  0.058749  0.753386  0.490354
H  0.670039  0.613087  0.078218  0.022264  0.611517

In [12]:
df1["Score1"]

A    0.244003
B    0.924249
C    0.033633
D    0.493485
E    0.558038
F    0.366130
G    0.461912
H    0.670039
Name: Score1, dtype: float64

In [14]:
df1[["Score1","Score2"]]

Score1    Score2
A  0.244003  0.261064
B  0.924249  0.350629
C  0.033633  0.303336
D  0.493485  0.134175
E  0.558038  0.527210
F  0.366130  0.239166
G  0.461912  0.181772
H  0.670039  0.613087

In [18]:
df1['Score6']=df1['Score1']+df1['Score2']+df1['Score3']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.244003  0.261064  0.484532  0.439343  0.440695  0.989599
B  0.924249  0.350629  0.451532  0.920795  0.501744  1.726410
C  0.033633  0.303336  0.295935  0.778055  0.478633  0.632904
D  0.493485  0.134175  0.533664  0.849704  0.948651  1.161324
E  0.558038  0.527210  0.705029  0.135567  0.916620  1.790277
F  0.366130  0.239166  0.099890  0.332609  0.456562  0.705186
G  0.461912  0.181772  0.058749  0.753386  0.490354  0.702433
H  0.670039  0.613087  0.078218  0.022264  0.611517  1.361344

In [20]:
df2={'ID':['405','509','890'],'Name':['Janvi','Shiven','Arpita'],'Profit':[50,90,45]}
df=pd.DataFrame(df2)
df

ID    Name  Profit
0  405   Janvi      50
1  509  Shiven      90
2  890  Arpita      45

In [21]:
df['ID']

0    405
1    509
2    890
Name: ID, dtype: object

In [22]:
df[["ID","Name"]]

ID    Name
0  405   Janvi
1  509  Shiven
2  890  Arpita

In [30]:
df.drop(1)

Profit
0      50
2      45